name: "bb_ci"
description: "automate smart contract deployments across multiple networks using BuildBear’s sandbox"

inputs:               - name: bb_ci
                uses: BuildBearLabs/buildbear_x_action@v1.3.0
            
  network:
    description: "List of networks you want to deploy on"
    required: true
  deploy-command:
    description: "Command to deploy the contract"
    required: true
  buildbear-token:
    description: "Buildbear API token"
    required: true
  working-directory:
    description: "Project directory"
    required: false
    default: "."

outputs:
  deployments:
    description: "deployments logs"

runs:
  using: "node20"
  main: "index.js"

branding:
  icon: "bold"
  color: "green"
